title: Personal site of MMK
author: Mahdee Mushfique Kamal
email: mmkdhrubo@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is a minimal personal website of Mahdee Mushfique Kamal. I am studying Computer Science and Engineering in Bangladesh University of Engineering and Technology.
  This site contains my curriculum vitae, contact information, academic and side projects.
  This site is inteded to host on github.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Mahdee Mushfique Kamal
  #tagline: Developer. Designer
  disqus_shortname: mahdeemushfiquekamal
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/MMK.jpg" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  navigation:
    - title: CV
      url: "/cv"
    - title: Projects
      url: "/projects"
    - title: Contact Info
      url: "/contact"
  # generate social links in footer
  social_links:
    #twitter: DhruboKamal
    github:  DhruboKamal
    linkedIn: in/mmkdhrubo
    facebook: mmk.dhrubo
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
  analytics_id: "G-JD3Y9RVBW7"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: samarsault/plainwhite-jekyll
#theme: plainwhite

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

#  - jekyll-spaceship
#  - jekyll-feed


paginate: 5
paginate_path: "/post/page:num/"

